name: Build Executable

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform: 
        - { os: windows-2022, cmake-flags: '-G"Visual Studio 17"' }
        - { os: ubuntu-latest }

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - name: Checkout SFML
      uses: actions/checkout@v2
      with:
        repository: 'SFML/SFML'
        path: './.SFML'

    - name: Cache SFML
      id: sfml
      uses: actions/cache@v2
      with:
        path: ./.SFML/.build
        key: SFML-${{ runner.os }}-${{ matrix.platform.cmake-flags }}-${{ hashFiles('./.SFML/**/*.hpp') }}

    - name: Configure cmake SFML
      if: steps.sfml.outputs.cache-hit != 'true'
      run: cmake ${{ matrix.platform.cmake-flags }} -DCMAKE_BUILD_TYPE=Debug -B./.SFML/.build ./.SFML

    - name: Build SFML
      if: steps.sfml.outputs.cache-hit != 'true'
      run: cmake --build ./.SFML/.build --config=Debug

    - name: Install SFML
      run: cmake --install ./.SFML/.build --config=Debug

    - name: Checkout Box2D
      uses: actions/checkout@v2
      with:
        repository: 'erincatto/box2d'
        path: './.box2d'

    - name: Cache Box2D
      id: box2d
      uses: actions/cache@v2
      with:
        path: ./.box2d/.build
        key: Box2D-${{ runner.os }}-${{ matrix.platform.cmake-flags }}-${{ hashFiles('./.box2d/**/*.h') }}
 
    - name: Configure cmake Box2D
      if: steps.box2d.outputs.cache-hit != 'true'
      run: cmake ${{ matrix.platform.cmake-flags }} -DCMAKE_BUILD_TYPE=Debug -B./.box2d/.build ./.box2d

    - name: Build Box2D
      if: steps.box2d.outputs.cache-hit != 'true'
      run: cmake --build ./.box2d/.build --config=Debug

    - name: Install Box2D
      run: cmake --install ./.box2d/.build --config=Debug

    - name: Configure Project
      run: cmake ${{ matrix.platform.cmake-flags }} -DCMAKE_BUILD_TYPE=Debug -B./.build .

    - name: Build Project
      run: cmake --build ./.build --config=Debug
